package com.moriba.skultem.domain.model;

import java.math.BigDecimal;
import java.time.Instant;

import com.moriba.skultem.domain.shared.AggregateRoot;

import lombok.Getter;

/**
 * A cash sale of a school material (uniform, socks, textbook, etc.) - independent of the
 * fee/entitlement flow that {@link Supply} covers. A sale may or may not be tied to a
 * {@link Student}: a walk-in buyer (e.g. a guardian buying a spare uniform) is recorded with just
 * a {@link #customerName} instead.
 *
 * A sale never deducts stock itself - every sale is backed by a linked {@link Supply} record
 * ({@link #supplyId}), created alongside it (see {@code CreateMaterialSaleUseCase}), and stock is
 * only ever deducted when that Supply is collected (see {@code SupplyMaterialUseCase}) - the exact
 * same mechanism a fee-entitled Supply already used. Schools routinely pre-sell items they haven't
 * been supplied yet - money changes hands today for stock that arrives next week. Rather than
 * force every sale to wait on inventory, a sale that outstrips what's on the shelf is created as
 * {@link Status#PENDING_SUPPLY} ("to settle later") with its linked Supply left uncollected, and
 * is later moved to {@link Status#FULFILLED} once that Supply is actually collected. See
 * {@link #fulfill()}.
 */
@Getter
public class MaterialSale extends AggregateRoot<String> {

    private String schoolId;
    private Student student;
    private String customerName;
    private Material material;
    private int quantity;
    private BigDecimal unitPrice;
    private BigDecimal totalAmount;
    private BigDecimal amountPaid;
    private PaymentMethod paymentMethod;
    private String note;
    private Status status;
    private Instant fulfilledAt;
    // The Supply record that actually owns stock deduction/collection for this sale - see the
    // class-level note above.
    private String supplyId;

    public enum Status {
        // Stock wasn't available at sale time - the item is still owed to the buyer.
        PENDING_SUPPLY,
        // The item has been handed over and stock was deducted.
        FULFILLED,
        CANCELLED
    }

    public enum PaymentMethod {
        CASH,
        BANK,
        MOBILE_MONEY
    }

    public enum PaymentStatus {
        UNPAID,
        PARTIAL,
        PAID
    }

    public MaterialSale(String id, String schoolId, Student student, String customerName, Material material,
            int quantity, BigDecimal unitPrice, BigDecimal totalAmount, BigDecimal amountPaid,
            PaymentMethod paymentMethod, String note, Status status, Instant fulfilledAt, String supplyId,
            Instant createdAt, Instant updatedAt) {
        super(id, createdAt);
        this.schoolId = schoolId;
        this.student = student;
        this.customerName = customerName;
        this.material = material;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
        this.totalAmount = totalAmount;
        this.amountPaid = amountPaid != null ? amountPaid : BigDecimal.ZERO;
        this.paymentMethod = paymentMethod;
        this.note = note;
        this.status = status;
        this.fulfilledAt = fulfilledAt;
        this.supplyId = supplyId;
        touch(updatedAt);
    }

    // FACTORY METHOD
    // `fulfilledNow` is decided by the use case from the material's current stock level.
    // `supplyId` is the id of the Supply record the use case creates alongside this sale (and
    // immediately collects, if fulfilledNow) - it must already exist by the time this is called.
    // `id` is generated by the caller (rather than here) because that Supply needs this sale's id
    // as its own sourceSaleId before this sale object even exists - see CreateMaterialSaleUseCase.
    public static MaterialSale create(String id, String schoolId, Student student, String customerName,
            Material material, int quantity, BigDecimal unitPrice, BigDecimal amountPaid,
            PaymentMethod paymentMethod, String note, boolean fulfilledNow, String supplyId) {

        if (student == null && (customerName == null || customerName.isBlank())) {
            throw new IllegalArgumentException("A sale must be linked to a student or have a customer name");
        }

        if (quantity <= 0) {
            throw new IllegalArgumentException("Quantity must be greater than zero");
        }

        if (unitPrice == null || unitPrice.compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException("Unit price cannot be negative");
        }

        BigDecimal total = unitPrice.multiply(BigDecimal.valueOf(quantity));
        BigDecimal paid = amountPaid != null ? amountPaid : BigDecimal.ZERO;

        if (paid.compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException("Amount paid cannot be negative");
        }

        if (paid.compareTo(total) > 0) {
            throw new IllegalArgumentException("Amount paid cannot exceed the total sale amount");
        }

        if (paid.compareTo(BigDecimal.ZERO) > 0 && paymentMethod == null) {
            throw new IllegalArgumentException("Payment method is required when an amount is paid");
        }

        Instant now = Instant.now();
        Status status = fulfilledNow ? Status.FULFILLED : Status.PENDING_SUPPLY;

        return new MaterialSale(
                id,
                schoolId,
                student,
                student == null ? customerName.trim() : null,
                material,
                quantity,
                unitPrice,
                total,
                paid,
                paymentMethod,
                note,
                status,
                fulfilledNow ? now : null,
                supplyId,
                now,
                now);
    }

    // Adds a further payment towards the sale's balance - used when a pre-sale was collected
    // partially up front and the buyer settles the rest before or after the item is fulfilled.
    public void recordPayment(BigDecimal amount, PaymentMethod method) {
        if (status == Status.CANCELLED) {
            throw new IllegalStateException("Cannot record a payment on a cancelled sale");
        }

        if (amount == null || amount.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException("Payment amount must be greater than zero");
        }

        BigDecimal balance = getBalance();

        if (amount.compareTo(balance) > 0) {
            throw new IllegalArgumentException("Payment exceeds the outstanding balance of " + balance);
        }

        this.amountPaid = this.amountPaid.add(amount);
        this.paymentMethod = method != null ? method : this.paymentMethod;

        touch(Instant.now());
    }

    // Marks a pre-sold item as handed over now that stock is available - stock is deducted by the
    // use case, mirroring Supply.collect()/SupplyMaterialUseCase.
    public void fulfill() {
        if (status == Status.CANCELLED) {
            throw new IllegalStateException("Cannot fulfill a cancelled sale");
        }

        if (status == Status.FULFILLED) {
            throw new IllegalStateException("Sale is already fulfilled");
        }

        this.status = Status.FULFILLED;
        this.fulfilledAt = Instant.now();

        touch(Instant.now());
    }

    // Only a pre-sale still awaiting stock can be cancelled outright - a FULFILLED sale already
    // handed stock to the buyer, and unwinding that is a return/refund, a different flow than this
    // one covers.
    public void cancel() {
        if (status == Status.FULFILLED) {
            throw new IllegalStateException("Cannot cancel a sale that has already been fulfilled");
        }

        if (status == Status.CANCELLED) {
            throw new IllegalStateException("Sale is already cancelled");
        }

        this.status = Status.CANCELLED;
        touch(Instant.now());
    }

    public BigDecimal getBalance() {
        return totalAmount.subtract(amountPaid);
    }

    public PaymentStatus getPaymentStatus() {
        if (amountPaid.compareTo(BigDecimal.ZERO) <= 0) return PaymentStatus.UNPAID;
        if (amountPaid.compareTo(totalAmount) >= 0) return PaymentStatus.PAID;
        return PaymentStatus.PARTIAL;
    }
}
