POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "domain": "kings-way",
  "email": "ishmaelkargbo5@outlook.com",
  "password": "Isho@2024"
}

###
POST http://localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyZjM4Y2E2ZS1iZmE5LTQ4OTYtYWRjNy1hNmVjM2U0NTQ2MjUiLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc3MzQwMTkxMCwiZXhwIjoxNzc0MDA2NzEwfQ.J_HzX0IAvUbePwMkXepiVtk0HDsfbbbcV-lcpH9Odrc"
}
