POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "domain": "kings-way",
  "email": "ishmaelkargbo5@outlook.com",
  "password": "Isho@2024"
}

###
POST http://localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmYWEwNzhiZC1kNzJiLTQyYjQtOTczMC1kNzIyYmU1YTliOGUiLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc3Mzc0MDI5MSwiZXhwIjoxNzc0MzQ1MDkxfQ.2X9ZTHJ_sEKuWZV2tcSKttNMHyUXv6bwttEgz8nfan0"
}
