POST http://localhost:8080/api/v1/parent
Content-Type: application/json
X-User-Id: USR-2026-0001
X-School-Id: SCL-2026-0001

{
  "city": "Freetown",
  "phone": "+23276573898",
  "email": "mohamedkamara@gmail.com",
  "givenNames": "Mohamed",
  "familyName": "Kamara",
  "fatherName": "Mohamed Kamara",
  "motherName": "Bintu Kamara",
  "street": "105 Free Street"
}


###
GET http://localhost:8080/api/v1/parent?&size=10
X-User-Id: USR-2026-0001
X-School-Id: SCL-2026-0001

###
GET http://localhost:8080/api/v1/academic_year/ACY-2026-0001
X-User-Id: USR-2026-0001
X-School-Id: SCL-2026-0001

###
PUT http://localhost:8080/api/v1/academic_year/ACY-2026-0001