###
POST http://localhost:8080/api/v1/report/export/run?page=1&size=200
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU1ItMjAyNi0wMDAxIiwic2NoIjoiU0NMLTIwMjYtMDAwMSIsInNpZCI6ImI1ODE5OGVlLWFiN2QtNGFkZi04YWI4LWUxN2MzZmQ3ZDFhOSIsInJvbGVzIjpbIlNDSE9PTF9BRE1JTiJdLCJpYXQiOjE3NzM1MDQ4MDgsImV4cCI6MTc3MzUwNTcwOH0.FwLfeOo3VequtKeWTJGep4C4GBKk14zf_2LydYQfpIg
Content-Type: application/json

{
  "entity": "students",
  "filters": [
    {
      "field": "class",
      "operator": "EQUALS",
      "value": "CLS-2026-0003"
    },
    {
      "field": "gender",
      "operator": "EQUALS",
      "value": "FEMALE"
    }
  ]
}

###
GET http://localhost:8080/api/v1/dashboard/admin/weekly-attendance
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU1ItMjAyNi0wMDAxIiwic2NoIjoiU0NMLTIwMjYtMDAwMSIsInNpZCI6IjkwNmY2MDdmLWRiNWYtNDBjMS1hYzc1LTgzYzdkMzVkODE0NSIsInJvbGVzIjpbIlNDSE9PTF9BRE1JTiJdLCJpYXQiOjE3NzMwMDQ1NzksImV4cCI6MTc3MzAwNTQ3OX0.AHL_nDGQy88ANnRHLRvo2AeuuzsgzLgTonD5XvUgVhI

###
GET http://localhost:8080/api/v1/dashboard/admin/student-enrollment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU1ItMjAyNi0wMDAxIiwic2NoIjoiU0NMLTIwMjYtMDAwMSIsInNpZCI6IjkwNmY2MDdmLWRiNWYtNDBjMS1hYzc1LTgzYzdkMzVkODE0NSIsInJvbGVzIjpbIlNDSE9PTF9BRE1JTiJdLCJpYXQiOjE3NzMwMDU4ODAsImV4cCI6MTc3MzAwNjc4MH0.NR7F5dmqROqm4TtrU3q2DhDA-CQFwaoKiiGoNDGa9QA


###
GET http://localhost:8080/api/v1/dashboard/admin/revenue
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU1ItMjAyNi0wMDAxIiwic2NoIjoiU0NMLTIwMjYtMDAwMSIsInNpZCI6IjkwNmY2MDdmLWRiNWYtNDBjMS1hYzc1LTgzYzdkMzVkODE0NSIsInJvbGVzIjpbIlNDSE9PTF9BRE1JTiJdLCJpYXQiOjE3NzMwMTE2NTgsImV4cCI6MTc3MzAxMjU1OH0.kiMJ0anAO8QSAdq_-3b1vMhsfUFV2CDLiYQwqimQCko
###
PUT http://localhost:8080/api/v1/academic_year/ACY-2026-0001