POST http://localhost:8080/api/v1/section
Content-Type: application/json

{
  "school": "SCL-2026-0001",
  "name": "Yellow",
  "classId": "CLS-2026-0001"
}

###
GET http://localhost:8080/api/v1/section?size=10
X-User-Id: USR-2026-0001
X-School-Id: SCL-2026-0001

###
GET http://localhost:8080/api/v1/section/class/CLS-2026-0001?size=10
X-User-Id: USR-2026-0001
X-School-Id: SCL-2026-0001

###
GET http://localhost:8080/api/v1/class/CLS-2026-0001