
POST http://localhost:8080/api/v1/assignment/class/CLS-2026-0001
Content-Type: application/json
X-User-Id: USR-2026-0001
X-School-Id: SCL-2026-0001

{
  "assignments": [
    {
      "subjectId": "SUB-2026-0001",
      "mandatory": true
    },
    {
      "subjectId": "SUB-2026-0002",
      "mandatory": true
    }
  ]
}


###
POST http://localhost:8080/api/v1/assignment/stream/STM-2026-0001
Content-Type: application/json
X-User-Id: USR-2026-0001
X-School-Id: SCL-2026-0001

{
  "assignments": [
    {
      "subjectId": "SUB-2026-0001",
      "mandatory": true
    },
    {
      "subjectId": "SUB-2026-0002",
      "mandatory": true
    },
    {
      "subjectId": "SUB-2026-0003",
      "mandatory": false
    }
  ]
}